stages:
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myweb
      pushRemote: true
      registry: harbor.big2.com
timeout: 60
notification: {}
