stages:
- name: deploy
  steps:
  - publishCatalogConfig:
      path: ./
      catalogTemplate: TEST001
      version: V2
      gitUrl: https://github.com/pigliangliang/
      gitBranch: master
      gitAuthor: zhu
      gitEmail: ZHU@qq.com
    envFrom:
    - sourceName: piggithub
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: piggithub
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
