stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myweb
      registry: 127.0.0.1:34646
- name: deploy
  steps:
  - publishCatalogConfig:
      path: ./
      catalogTemplate: TEST001
      version: V2
      gitUrl: https://github.com/pigliangliang/untitled56.git
      gitBranch: master
      gitAuthor: zhu
      gitEmail: ZHU@qq.com
    envFrom:
    - sourceName: piggithubsecret
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: piggithubsecret
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
